### PR TITLE
Allow user-defined browsers in $HOME/.config/psd/browsers

### PR DESCRIPTION
**Pull request by Xervon**
As @ryanerwin mentioned in #240 I also wanted the ability to add a custom browser or override a default browser configuration within my user config directory.

The current version of the code therefore changes the following:
1. f no browsers are defined, it defaults to all stock and user browsers
2. For every defined browser it first checks, if there is a user provided config
   * If there is it sources that
   * Otherwise it loads the default config

### CODE REVIEW

**Comment by Alexander-Shukaev** [comment]
Looking forward as well!

**Comment by Xervon** [comment]
Any chance of this still being merged with commit ff34411 having been merged @graysky2?

I'd like to keep custom browser definitions in my personal dotfiles and be able to add custom profiles as a normal (non-root) user.

**Comment by Alexander-Shukaev** [comment]
I guess this one can be closed in favor of fix from #240.

**Comment by Xervon** [comment]
Personally I'd really like to have the ability to define my custom profiles within my home directory where all of the other configuration is done as well.I want to be able to synchronize my custom profiles the same way I do the rest of my personal dotfiles.

Defining user profiles in my home directory also allows any user to add their personal profiles without needing root privileges.

**Comment by felipec** [comment]
Until this is merged or Brave is in `/usr/share/psd/browsers/` I won't consider psd useful to me. I'm not going to modify `/usr/share/`.

**Comment by graysky2** [comment]
@felipec - There isn't much value you sharing your opinion in 3 (counting this one) different closed PRs.  Don't use psd if my decision to require users to copy a template to a root owned directory offends you.

https://github.com/graysky2/profile-sync-daemon/issues/233#issuecomment-835872064
https://github.com/graysky2/profile-sync-daemon/pull/240#issuecomment-835872647

**Comment by Xervon** [comment]
For those that have an interest in this feature, my forked version of this is now once again up to date with this repo. @felipec if you're willing to install this from source that might serve your use case.

[Xervon/profile-sync-daemon](https://github.com/Xervon/profile-sync-daemon)

I for one have been using my fork without any issues pretty much since I've made this pull request.

**Comment by felipec** [comment]
@graysky2:

> There isn't much value you sharing your opinion in 3 (counting this one) different closed PRs.

I will decide which of my actions have value. You are free to disagree.

> Don't use psd if my decision to require users to copy a template to a root owned directory offends you.

It doesn't offend me to do wrong things. But they are still wrong.

And yeah, I won't use **your** psd.

@Xervon:

> For those that have an interest in this feature, my forked version of this is now once again up to date with this repo.

Thank you, I created an Arch Linux package of your fork: [profile-sync-daemon-user](https://aur.archlinux.org/packages/profile-sync-daemon-user/), and it does indeed work fine with my user configuration of the Brave browser.

I sent you a small fix since I found it annoying that `find` throws an error message if the user browsers directory doesn't exist: Xervon/profile-sync-daemon#1.

**Comment by Xervon** [comment]
> and use a different branch for the pull request (not master).
True. I don't believe I can actually change this at this point. Hopefully closing this will prevent the updates being shown here.

**Comment by Alexander-Shukaev** [comment]
Brave is in `contrib` already.  What's your problem?  You can also contribute any browser for everyone to use.

**Comment by felipec** [comment]
> Brave is in `contrib` already. What's your problem? You can also contribute any browser for everyone to use.

That is useless to me.

Does psd pick browser configurations from `contrib`?

**Pull request closed without merging**
