### PR TITLE
minor edits

### PR DESCRIPTION
**Pull request by amagnasco**
Hi Graysky,

I love the program! I just edited a couple of things for legibility:
1) slight rewrite of INSTALL, and 2) merged MIT into LICENSE

Best,
Alessandro

### CODE REVIEW

**Comment by graysky2** [comment]
Sorry, forgot about your PR.  Will check it out.  I thought I had some reason for breaking out the two licenses relating to Fedora requirements...

**Comment by graysky2** [comment]
I just fixed the spelling error.  Probably don't need to comment the file since it's not a script.

**Comment by amagnasco** [comment]
True, I just naturally write that way I guess. Force of habit. You're always on the arch forums, right?

**Comment by graysky2** [comment]
Should be able to find me there.

**Comment by amagnasco** [comment]
cool beans. great software man, kudos!

**Pull request closed without merging**
