### PR TITLE
Add ovfs sync to lowerdir workaround

### PR DESCRIPTION
**Pull request by Nefelim4ag**

### CODE REVIEW

**Comment by graysky2** [comment]
Merged into my unstable branch.

**Comment by graysky2** [comment]
@Nefelim4ag - I'm confused... where on the filesystem is BACK_OVFS?

**Comment by Nefelim4ag** [comment]
@graysky2,
lrwxrwxrwx 1 nefelim4ag users    39 Oct 25 20:10 google-chrome -> /run/user/1000/nefelim4ag-google-chrome
drwx------ 1 nefelim4ag users  1960 Oct 26 01:13 google-chrome-back-ovfs
drwx------ 1 nefelim4ag users  1960 Oct 25 20:08 google-chrome-backup

**Comment by graysky2** [comment]
I don't see it for chromium...
```
ls -lh ~/.config/ | grep chrom
drwx------ 11 facade users 4.0K Oct 25 17:44 chromium-backup
lrwxrwxrwx  1 facade users   31 Oct 25 17:45 chromium -> /run/user/1000/facade-chromium
-rw-r--r--  1 facade users   30 May 25 05:15 chromium-flags.conf

psd p | sed 's/squishy/facade/g'
Profile-sync-daemon v6.12.r2.gf49c743.unstable on Arch Linux

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs v23 is currently active.

Psd will manage the following per /home/facade/.config/psd/psd.conf:

 browser/psname:  chromium/chromium
 owner/group id:  facade/100
 sync target:     /home/facade/.config/chromium
 tmpfs dir:       /run/user/1000/facade-chromium
 profile size:    72M
 overlayfs size:  37M
 recovery dirs:   none
```

**Comment by FadeMind** [comment]
[tomasz@arch ~]$ ls -lh ~/.config/ | grep chrome
    drwx------ 10 tomasz users 4,0K 25.10.2015 22:59 google-chrome-back-ovfs/
    drwx------ 10 tomasz users 4,0K 25.10.2015 22:59 google-chrome-backup/
    lrwxrwxrwx  1 tomasz users   35 25.10.2015 22:59 google-chrome -> /run/user/1000/tomasz-google-chrome/
    [tomasz@arch ~]$ psd p 
    Profile-sync-daemon v6.12.r2.gf49c743.unstable on Arch Linux
    
     Systemd service is currently active.
     Systemd resync-timer is currently active.
     Overlayfs v23 is currently active.
    
    Psd will manage the following per /home/tomasz/.config/psd/psd.conf:
    
     browser/psname:  google-chrome/chrome
     owner/group id:  tomasz/100
     sync target:     /home/tomasz/.config/google-chrome
     tmpfs dir:       /run/user/1000/tomasz-google-chrome
     profile size:    267M
     overlayfs size:  64M
     recovery dirs:   none

**Comment by graysky2** [comment]
No idea why my shit isn't working.

**Comment by graysky2** [comment]
@FadeMind 
@Nefelim4ag 

Can you guys please check out the follow... since we now have two potential backups (either BACKUP or BACKOVFS) we need some logic to select which is newest in case of a crash for recovery purposes:

https://github.com/graysky2/profile-sync-daemon/compare/b51961b0d4c6aced24592b3f04143cfa0d6fcf12...fad0849ac5a3accf8836f9c6f8a2ae27adce2d3f

**Comment by Nefelim4ag** [comment]
@graysky2, whats happen if user use noatime?

**Comment by graysky2** [comment]
I tested both relatime and noatime in a VM using ext4 and in each case, the
last access was returned by stat.

On Tuesday, November 3, 2015, Timofey <notifications@github.com> wrote:

> @graysky2 <https://github.com/graysky2>, whats happen if user use noatime?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/graysky2/profile-sync-daemon/pull/149#issuecomment-153423126>
> .
>


-- 
Sent from Gmail Mobile

**Pull request closed without merging**
