### PR TITLE
add service file for pre/post system suspend/hibernate actions

### PR DESCRIPTION
**Pull request by lots0logs**
AFAICT, this should ensure that unsync is performed prior to system sleep and also that a resync is performed upon waking from sleep. (RE: #141 )

### CODE REVIEW

**Comment by graysky2** [comment]
Have you tested it to verify?

**Comment by lots0logs** [comment]
@graysky2 Yeah, I had the same concern about adding an additional service but I don't see any way around it. I havent fully tested it yet. I have the extra service file in-place but I'm working at the moment. I'll let you know the result asap.

**Comment by graysky2** [comment]
Cool, please let me know how your testing goes.

**Comment by graysky2** [comment]
https://github.com/graysky2/profile-sync-daemon/issues/141

**Pull request closed without merging**
