### PR TITLE
Release inhibit lock

### LINKED ISSUE #63: why psd not manage .cache?
I think all browser content must be on ram, may be i mistake?
google-chrome writes and uses and uses ~/.cache/google-chrome

### LINKED ISSUE #275: [Bug] Sync before suspend does not release inhibit lock
```
Linux ArcoB 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64 GNU/Linux
Profile-sync-daemon v6.42
```

I've been noticing that my system takes a significant amount of time to sleep after I initiate the sleep process. After some research, I have come to the conclusion that it is being caused by `psd` not releasing the inhibit delay lock it acquires when the system is about to sleep.

Before I press the sleep button, you can see that `psd` registers some sort of inhibitor:

```
➜ systemd-inhibit --list
WHO                 UID  USER       PID    COMM            WHAT                                                                       WHY                                       MODE 
profile-sync-daemon 1000 chigozirim 629467 systemd-inhibit sleep                                                                      psd resync on suspend                     delay
```

When the system is about to sleep, we can see the following events:

```
Oct 06 14:29:09 ArcoB systemd-logind[934]: Suspend key pressed.
Oct 06 14:29:09 ArcoB root[638283]: SleepButton pressed
```

Next, we see `psd` start the syncing process:

```
Oct 06 14:29:09 ArcoB chigozirim[638287]: [psd-suspend-sync] Issueing suspend-sync request...
Oct 06 14:29:09 ArcoB profile-sync-daemon[638291]: firefox resync successful
Oct 06 14:29:09 ArcoB profile-sync-daemon[638291]: firefox resync successful
Oct 06 14:29:09 ArcoB profile-sync-daemon[638291]: vivaldi resync successful
```

At this point, `psd` has not released the lock, which leads the machine to wait until [`InhibitDelayMaxSec`](https://www.freedesktop.org/software/systemd/man/logind.conf.html#InhibitDelayMaxSec=) (5 seconds) expires, and then we see:

```
Oct 06 14:29:14 ArcoB systemd-logind[934]: Delay lock is active (UID 1000/chigozirim, PID 629467/systemd-inhibit) but inhibitor timeout is reached.
```

Only at this point does the system finally sleep.

---

P.S. It would be nice if there is some logging that goes on when the lock is released to the system.

### PR DESCRIPTION
**Pull request by smac89**
Fixes #275

### CODE REVIEW

**Comment by graysky2** [comment]
Please rebase/squash into a single commit.
@glitsj16 - Any thoughts on this PR?

**Comment by glitsj16** [comment]
@graysky2 I'll take a closer look at this tomorrow. Need some sleep right now.

**Comment by smac89** [comment]
Can we get a go ahead on this? I've been using this fix on my machine since I posted it here, and it has been working fine. In fact I tested it first on my machine.

If there is any questions, I can answer them to the best of my knowledge.

**Comment by graysky2** [comment]
@glitsj16 - Any thoughts on this PR?

**Comment by glitsj16** [comment]
@graysky2 Apologies for not responding earlier, been swamped with work and family stuff lately. I see no reason to doubt @smac89's observations, so IMO this can be merged.

**Comment by graysky2** [comment]
Thank you both for the effort.

**Pull request merged**
